"use strict";

let questions = [
    new Question("Rozdělení EZ podle napětí mezi vodiči v uzemněné střídavé soustavě je:", ["mn do 50 V; nn do 1000 V; vn do 52 kV", "b", "c", "d"], 0),
    new Question("Jmenovité napětí střídavých rozvodných sítí v ČR je:", ["230/400 V"], 0),
    new Question("Mez bezpečných jmenovitých napětí při předpokládaném dotyku neživých částí v prostorech normálních je:", ["50 V~ a 120 V="], 0),
    new Question("Dovolené meze trvalého dotykového napětí v prostorech normálních i nebezpečných pro EZ do 1000 V jsou:", ["25 V~ a 60 V="], 0),
    new Question("Odpor uzemnění uzlu zdroje nemá být větší než:", ["5 Ω, ve ztížených podmínkách nejvýše 15 Ω"], 0),
    new Question("Plynové potrubí se jako náhodný ochranný vodič:", ["nesmí použít"], 0),
    new Question("Silnoproudá zařízení jsou zařízení:", ["u nichž mohou vzniknout proudy nebezpečné osobám, zvířatům a věcem"], 0),
    new Question("Obecná charakteristika prostorů nebezpečných říká, že:", ["vlivem prostředí je zde stálé nebo přechodné nebezpečí úrazu elektrickým proudem"], 0),
    new Question("Z hlediska možného zvýšení rizika úrazu elektrickým proudem působením vnějších vlivů se prostory člení na:", ["normální, nebezpečné a zvlášť nebezpečné"], 0),
    new Question("Barva bezpečnostních tabulek výstrahy je:", ["žlutá"], 0),
    new Question("Barva bezpečnostních tabulek zákazu je:", ["červená"], 0),
    new Question("Bezpečnostní značka v provedení modrý kruh, bílý symbol je značka:", ["příkazu"], 0),
    new Question("Bezpečnostní značky v provedení na zeleném podkladu jsou značky:", ["informační"], 0),
    new Question("V označení stupně krytí IP udává první číslice:", ["stupeň ochrany osob před nebezpečným dotykem živých částí a stupeň ochrany zařízení před vniknutím cizích pevných těles"], 0),
    new Question("Prostředky základní ochrany (před přímým dotykem) EZ zajišťují ochranu:", ["jen při normálním provozu"], 0),
    new Question("Prostředky zvýšené ochrany (před přímým i nepřímým dotykem) EZ zajišťují ochranu:", ["základní i při poruše"], 0),
    new Question("Při ochraně automatickým odpojením se pro střídavé rozvodné sítě do 1000 V dovoluje doba odpojení:", ["nepřesahující 5 s"], 0),
    new Question("Pro automatické odpojení od zdroje v síti TT 230 V AC, zajišťující ochranu před nepřímým dotykem koncového obvodu do 32 A, musí ochranný prvek vypnout v čase do:", ["0,2 s."], 0),
    new Question("Pro automatické odpojení od zdroje v síti TN 230 V AC, zajišťující ochranu před nepřímým dotykem koncového obvodu do 32 A, musí ochranný prvek vypnout v čase do:", ["0,4 s."], 0),
    new Question("Při základní ochraně krytím musí kryty:", ["být dostatečně odolné, vyhovující alespoň IPxxB (IP2X), horní vodorovné kryty pak IPxxD (IP4X), odstranitelné jen klíčem či nástrojem"], 0),
    new Question("Ochranu zábranou v prostorech volně přístupných laikům:", ["nelze použít"], 0),
    new Question("Napětí obvodů při ochranně elektrickým oddělením nesmí přesáhnout hodnotu:", ["500 V"], 0),
    new Question("Základní ochrana polohou spočívá:", ["v umístění živých částí mimo dosah"], 0),
    new Question("Doplňkovou ochranu proudovým chráničem lze realizovat:", ["chráničem se jmenovitým rozdílovým proudem nejvýše 30 mA"], 0),
    new Question("Proudové chrániče s rozdílovým proudem do 30 mA se musí požít na:", ["zásuvky se jmenovitým proudem do 32 A, které jsou používány laiky."], 0),
    new Question("Pro ochranu omezením ustáleného dotykového proudu a energie nesmí proud tekoucí odporem 2000 Ohmů mezi částmi současně přístupnými dotyku překročit hodnoty:", ["3,5 mA~ nebo 10 mA="], 0),
    new Question("Pro ochranu omezením ustáleného proudu a energie nesmí náboj mezi částmi současně přístupnými dotyku překročit hodnotu:", ["50 μC"], 0),
    new Question("Proudovým chráničem musí procházet:", ["všechny pracovní vodiče"], 0),
    new Question("Vidlice a zásuvky pro obvody SELV musí splňovat tyto požadavky:", ["nesmí být záměnné s vidlicemi a zásuvkami sítí jiných napětí a nesmí mít kontakt pro ochranný vodič"], 0),
    new Question("Živé části obvodů PELV s napětím nepřesahujícím 12V~ nebo 25V=:", ["nemusí mít základní ochranu"], 0),
    new Question("Jako zdroje pro ochranu malým napětím lze použít:", ["bezpečnostní ochranný transformátor, akumulátor"], 0),
    new Question("Obvody SELV:", ["nesmí být spojeny se zemí"], 0),
    new Question("Z označení PELV vyplývá, že jde o obvody:", ["uzemněné"], 0),
    new Question("Ochrana základní izolací znamená, že:", ["živé části musí být úplně pokryty izolací, kterou lze odstranit pouze jejím zničením"], 0),
    new Question("Zařízení mající dvojitou či zesílenou izolaci se označují jako:", ["EZ třídy ochrany II"], 0),
    new Question("Elektrické zařízení třídy ochrany II:", ["má dvojitou či zesílenou izolaci a nemá svorku pro připojení ochranného vodiče"], 0),
    new Question("Elektrické zařízení, u něhož je provedena jen pracovní izolace, se považuje z hlediska možného úrazu elektrickým proudem za zařízení:", ["bez ochrany"], 0),
    new Question("V sítích TT se neživé části EZ:", ["nesmějí připojit na nulový vodič"], 0),
    new Question("Elektrická zařízení třídy ochrany II musí mít připojovací vidlici:", ["bez ochranného vodiče"], 0),
    new Question("Elektrická zařízení třídy ochrany 0:", ["nelze v ČR používat"], 0),
    new Question("Izolace, která slouží k ochraně při poruše (před nepřímým dotykem) se nazývá:", ["přídavná"], 0),
    new Question("Pro připojení elektrických předmětů třídy ochrany I se dvouvodičový pohyblivý přívod s vidlicí bez ochranného kontaktu:", ["nesmí použít"], 0),
    new Question("Jednofázový pohyblivý prodlužovací přívod pro obecné použití se provede jako:", ["třížilový, přičemž ochranný vodič je veden samostatně a nesmí být spojen s nulovým vodičem"], 0),
    new Question("Barva izolovaných krajních (fázových) vodičů může být:", ["černá, hnědá nebo šedá"], 0),
    new Question("Fázové svorky elektrických předmětů a zařízení se ve střídavé rozvodné soustavě označují písmeny:", ["U, V, W"], 0),
    new Question("Nulový (střední) vodič střídavé soustavy se označuje:", ["N"], 0),
    new Question("Svorka ochranného vodiče se na elektrickém předmětu značí:", ["PE"], 0),
    new Question("Vodič PEN je:", ["vodič slučující funkci ochranného vodič a nulového vodiče"], 0),
    new Question("Jištění vodičů PE a PEN:", ["je zakázáno"], 0),
    new Question("Obsluha je taková činnost na EZ, kdy:", ["pracovník nepoužívá nástrojů a nemůže přijít do styku s živými částmi"], 0),
    new Question("Práce je taková činnost na EZ, kdy:", ["pracovník používá nástrojů a může přijít do styku s živými částmi"], 0),
    new Question("§4 Vyhlášky 50/1978 Sb. stanovuje požadavky pro kvalifikaci:", ["pracovníků poučených"], 0),
    new Question("§5 Vyhlášky 50/1978 Sb. stanovuje požadavky pro kvalifikaci:", ["pracovníků znalých"], 0),
    new Question("Pracovníci poučení mohou na EZ pracovat:", ["v blízkosti nekrytých částí EZ nn pod napětím ve vzdálenosti větší než 20 cm s dohledem"], 0),
    new Question("Při práci pod dozorem odpovídá za dodržování bezpečnostních předpisů:", ["pracovník dozírající"], 0),
    new Question("Při práci s dohledem odpovídá za dodržování bezpečnostních předpisů:", ["pracovník provádějící činnost"], 0),
    new Question("Pro následky úrazu elektrickým proudem je rozhodující:", ["velikost proudu, který protéká tělem zasaženého"], 0),
    new Question("Za současně přístupné dotyku se považují části navzájem vzdálené:", ["méně než 2,5 m"], 0),
    new Question("Pracovními pomůckami jsou například:", ["měřicí přístroje, zkoušečky napětí a další předměty potřebné k práci či obsluze EZ"], 0),
    new Question("Ochrannými pomůckami jsou například:", ["ochranné izolační rukavice, izolační koberce a plošiny, ochranné brýle apod."], 0),
    new Question("Před použitím ochranných pomůcek je pracovník povinen:", ["přesvědčit se o jejich řádném stavu"], 0),
    new Question("Nepřímá srdeční masáž má být prováděna s frekvencí asi:", ["100 stlačení za minutu"], 0),
    new Question("Před započetím nepřímé srdeční masáže je potřeba:", ["uložit postiženého rovně na záda na rovnou a pevnou podložku"], 0),
    new Question("Při provádění nepřímé srdeční masáže musí mít zachránce:", ["obě ruce napnuté v loktech"], 0),
    new Question("Při provádění nepřímé srdeční masáže je nutno stlačovat hrudní kost u dospělého člověka:", ["do hloubky 4-5 cm"], 0),
    new Question("Poměr stlačení srdce a umělého dýchání při resuscitaci má být:", ["30 stlačení a 2 vdechy"], 0),
    new Question("Automatický externí defibrilátor použijeme v případě:", ["zástavy dechu postiženého"], 0),
    new Question("Pokud postižený po úrazu elektrickým proudem dýchá a má hmatný tep, zůstává při vědomí a není viditelně zraněn:", ["je nutno přesto zavolat lékařskou pomoc"], 0),
    new Question("Záchrannou lékařskou službu je možné přivolat tísňovým telefonním číslem:", ["155"], 0),
    new Question("Jestliže postižený nabyl po resuscitaci vědomí:", ["musí být nadále sledován a musí zůstat vleže"], 0),
    new Question("Resuscitace se musí provádět:", ["dokud se neobnoví životní funkce nebo do předání postiženého do péče záchranářů"], 0)
];
